# Stubs for minio

from typing import Any

class Minio:
    def __init__(self, endpoint: str, access_key: str, secret_key: str, secure: bool = False) -> None: ...
    def bucket_exists(self, bucket_name: str) -> bool: ...
    def make_bucket(self, bucket_name: str) -> None: ...
    def remove_bucket(self, bucket_name: str) -> None: ...
    def list_buckets(self) -> list[Any]: ...

class S3Error(Exception):
    pass
