site_name: apiminio
repo_url: https://github.com/raederan/apiminio
site_url: https://raederan.github.io/apiminio
site_description: apiminio is a Python package that provides a ready-to-use REST API for interacting with MinIO S3 storage, built with FastAPI and the MinIO Python client. It enables seamless file uploads, downloads, and bucket management via HTTP interface ideal for integrating MinIO S3 into your applications with minimal setup.
site_author: Andreas Räder
edit_uri: edit/main/docs/
repo_name: raederan/apiminio
copyright: Maintained by <a href="https://raederan.com">raederan</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src/apiminio"]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/raederan/apiminio
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/apiminio

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
